-- 5 sports
INSERT INTO sports (sportName) VALUES ('Basketball');
INSERT INTO sports (sportName) VALUES ('Volleyball');
INSERT INTO sports (sportName) VALUES ('Baseball');
INSERT INTO sports (sportName) VALUES ('Soccer');
INSERT INTO sports (sportName) VALUES ('Football');

-- All passwords are asdf. 40 users
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('leka5026', 'leo', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('thbr4871', 'theo', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('zach2898', 'zach', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('jafr7644', 'jacob', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('japa2103', 'jaxon', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('brsa1000', 'brendan', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('nimo1000', 'nick', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('dede1000', 'destry', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('mimc1000', 'michael', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('cabi1000', 'carson', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('aufu1000', 'audrey', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('jacl1000', 'jackie', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('keol1000', 'kendall', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('frla1000', 'francesca', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('juda1000', 'julia', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('brvi1000', 'bryce', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('olda1000', 'olivia', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('jebu1000', 'jessie', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('pewo1000', 'peter', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('empu1000', 'emma', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('iztu1000', 'izzy', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('coru1000', 'cole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('cosm1000', 'cole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('keri1000', 'kenton', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('olsh1000', 'oliver', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('chpe1000', 'chas', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('koba1000', 'kole', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('alse1000', 'alex', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('alka1000', 'alex', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('iska1000', 'isaac', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('luka1000', 'lucy', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('frka1000', 'fred', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('tsch1000', 'tsion', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('moka1000', 'moira', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('deos1000', 'devyn', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('kixx1000', 'ki', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('tixx1000', 'ti', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2026, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('chtr1000', 'chloe', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2023, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('maka1000', 'marine', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2025, '', '2022-11-11');
INSERT INTO players (username, playerName, password, classYear, profilePhoto, joinDate) VALUES ('camo1000', 'carolina', '$2b$10$pSWjpntEzHInJozarXe4Z..5GM5QeUE/z3OEfK3NHdDS4tjPSj4Yu', 2024, '', '2022-11-11');

-- 20 teams
INSERT INTO teams (teamName) VALUES ('Alpha Sonics');
INSERT INTO teams (teamName) VALUES ('Venomous Busters');
INSERT INTO teams (teamName) VALUES ('Ghost Piledrivers');
INSERT INTO teams (teamName) VALUES ('Carnivore Xpress');
INSERT INTO teams (teamName) VALUES ('Silent Bombers');
INSERT INTO teams (teamName) VALUES ('Aero Planets');
INSERT INTO teams (teamName) VALUES ('Fire United');
INSERT INTO teams (teamName) VALUES ('Quicksilver Bullets');
INSERT INTO teams (teamName) VALUES ('Skull Buccaneers');
INSERT INTO teams (teamName) VALUES ('Blue Dreamers');
INSERT INTO teams (teamName) VALUES ('Reptile Assassins');
INSERT INTO teams (teamName) VALUES ('Zulu Bulls');
INSERT INTO teams (teamName) VALUES ('Samurai Spiders');
INSERT INTO teams (teamName) VALUES ('Aero Predators');
INSERT INTO teams (teamName) VALUES ('Knockout Bullets');
INSERT INTO teams (teamName) VALUES ('Dolphin Secret Agents');
INSERT INTO teams (teamName) VALUES ('Crimson Commando Squad');
INSERT INTO teams (teamName) VALUES ('Spinning Rebels');
INSERT INTO teams (teamName) VALUES ('Shaolin Sharpshooters');
INSERT INTO teams (teamName) VALUES ('Kamikaze Chuckers');

-- 100 games
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-20', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-21', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-22', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-23', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-24', '12:30', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-25', '12:45', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-26', '13:00', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-27', '13:05', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-28', '13:10', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-29', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2022-11-30', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-01', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-02', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-03', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-04', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-05', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-06', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-07', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-08', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-09', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-10', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-11', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-12', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-13', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-14', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-15', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-16', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-17', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-18', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-19', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-20', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-21', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-22', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-23', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-24', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-25', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-26', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-27', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-28', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-29', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2022-12-30', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-01', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-02', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-03', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-04', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-05', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-06', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-07', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-08', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-09', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-10', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-11', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-12', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-13', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-14', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-15', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-16', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-17', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-18', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-19', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-20', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-21', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-22', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-23', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-24', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-25', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-26', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-27', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-28', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-29', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2023-01-30', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-01', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-02', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-03', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-04', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-05', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-06', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-07', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-08', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-09', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-10', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-11', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-12', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-13', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-14', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-15', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-16', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-17', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-18', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-19', '13:15', 'j');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-20', '12:00', 'a');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-21', '12:05', 'b');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-22', '12:10', 'c');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-23', '12:15', 'd');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-24', '12:00', 'e');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-25', '12:30', 'f');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-26', '12:45', 'g');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-27', '13:00', 'h');
INSERT INTO games (gameDate, time, location) VALUES ('2023-02-28', '13:05', 'i');
INSERT INTO games (gameDate, time, location) VALUES ('2023-03-01', '13:15', 'j');

-- 20 Teams so 40 relations
INSERT INTO teamsToSports (teamID, sportID) VALUES (1, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (2, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (3, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (4, 1);
INSERT INTO teamsToSports (teamID, sportID) VALUES (5, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (6, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (7, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (8, 2);
INSERT INTO teamsToSports (teamID, sportID) VALUES (9, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (10, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (11, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (12, 3);
INSERT INTO teamsToSports (teamID, sportID) VALUES (13, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (14, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (15, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (16, 4);
INSERT INTO teamsToSports (teamID, sportID) VALUES (17, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (18, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (19, 5);
INSERT INTO teamsToSports (teamID, sportID) VALUES (20, 5);

-- 100 Games, 2 teams per game, so 200 Relations
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 1);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 1);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 6);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 6);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 11);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 11);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 16);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 16);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 21);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 21);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 26);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 26);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 31);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 31);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 36);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 36);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 41);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 41);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 46);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 46);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 51);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 51);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 56);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 56);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 61);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 61);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 66);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 66);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 71);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 71);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 76);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 76);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 81);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 81);
INSERT INTO teamsToGames (teamID, gameID) VALUES (1, 86);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 86);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 91);
INSERT INTO teamsToGames (teamID, gameID) VALUES (4, 91);
INSERT INTO teamsToGames (teamID, gameID) VALUES (3, 96);
INSERT INTO teamsToGames (teamID, gameID) VALUES (2, 96);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 2);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 2);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 7);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 7);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 12);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 12);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 17);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 17);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 22);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 22);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 27);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 27);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 32);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 32);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 37);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 37);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 42);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 42);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 47);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 47);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 52);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 52);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 57);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 57);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 62);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 62);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 67);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 67);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 72);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 72);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 77);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 77);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 82);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 82);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 87);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 87);
INSERT INTO teamsToGames (teamID, gameID) VALUES (8, 92);
INSERT INTO teamsToGames (teamID, gameID) VALUES (6, 92);
INSERT INTO teamsToGames (teamID, gameID) VALUES (7, 97);
INSERT INTO teamsToGames (teamID, gameID) VALUES (5, 97);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 3);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 3);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 8);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 8);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 13);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 13);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 18);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 18);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 23);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 23);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 28);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 28);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 33);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 33);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 38);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 38);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 43);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 43);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 48);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 48);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 53);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 53);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 58);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 58);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 63);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 63);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 68);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 68);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 73);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 73);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 78);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 78);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 83);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 83);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 88);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 88);
INSERT INTO teamsToGames (teamID, gameID) VALUES (11, 93);
INSERT INTO teamsToGames (teamID, gameID) VALUES (12, 93);
INSERT INTO teamsToGames (teamID, gameID) VALUES (9, 98);
INSERT INTO teamsToGames (teamID, gameID) VALUES (10, 98);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 4);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 4);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 9);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 9);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 14);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 14);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 19);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 19);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 24);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 24);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 29);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 29);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 34);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 34);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 39);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 39);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 44);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 44);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 49);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 49);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 54);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 54);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 59);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 59);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 64);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 64);
INSERT INTO teamsToGames (teamID, gameID) VALUES (16, 69);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 69);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 74);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 74);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 79);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 79);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 84);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 84);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 89);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 89);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 94);
INSERT INTO teamsToGames (teamID, gameID) VALUES (14, 94);
INSERT INTO teamsToGames (teamID, gameID) VALUES (13, 99);
INSERT INTO teamsToGames (teamID, gameID) VALUES (15, 99);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 5);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 5);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 10);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 10);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 15);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 15);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 20);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 20);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 25);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 25);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 30);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 30);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 35);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 35);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 40);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 40);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 45);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 45);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 50);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 50);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 55);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 55);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 60);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 60);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 65);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 65);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 70);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 70);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 75);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 75);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 80);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 80);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 85);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 85);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 90);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 90);
INSERT INTO teamsToGames (teamID, gameID) VALUES (20, 95);
INSERT INTO teamsToGames (teamID, gameID) VALUES (18, 95);
INSERT INTO teamsToGames (teamID, gameID) VALUES (19, 100);
INSERT INTO teamsToGames (teamID, gameID) VALUES (17, 100);

-- teams to players. 40 players 20 teams. have 5 people on each teach, so 100 relations
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (20, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (24, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (40, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (13, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 1);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (19, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (33, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (6, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (39, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 2);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (32, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 3);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (29, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 4);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (32, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (36, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 5);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (26, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (35, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 6);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (19, 7);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (6, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 8);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (19, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (40, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (31, 9);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (12, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (6, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 10);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (35, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (39, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (34, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (2, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 11);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (27, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (19, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (38, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (3, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 12);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (18, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (33, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (39, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (9, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 13);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (28, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (3, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (12, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 14);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (36, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (1, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 15);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (16, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (14, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (32, 16);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (17, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (35, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (36, 17);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (25, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (32, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (20, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (5, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (16, 18);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (26, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (10, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (7, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (37, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (8, 19);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (22, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (30, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (23, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (29, 20);
INSERT INTO teamsToPlayers (playerID, teamID) VALUES (21, 20);

-- Teams to Captains. 20 teams, each with 1 captain. 20 relatins
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (9, 1);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (35, 2);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (10, 3);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (25, 4);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (5, 5);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (27, 6);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (30, 7);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (8, 8);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (33, 9);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (22, 10);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (16, 11);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (30, 12);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (26, 13);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (5, 14);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (27, 15);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (29, 16);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (40, 17);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (27, 18);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (27, 19);
INSERT INTO teamsToCaptains (playerID, teamID) VALUES (16, 20);
